version: '3.8'
services:
  analysis:
    container_name: shellcast
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib/R/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/java-11-openjdk-amd64/lib/server
      - PROJ_LIB=/usr/share/proj
      - GDAL_DATA=/usr/share/gdal
    volumes:
      - ./analysis:/analysis
    restart: always

  cloudsql-proxy:
    container_name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.31.0
    command: /cloud_sql_proxy -dir=/cloudsql -instances=<Your Instance>=tcp:0.0.0.0:3306 -credential_file=/secrets/cloudsql/credentials.json
    ports:
      - 3306:3306
    volumes:
      - ./credentials.json:/secrets/cloudsql/credentials.json
    restart: always

# If you would like to test on local, comment "cloudsql-proxy" settings, and comment out "db" settings.
# Don't forget change variables.
#  db:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'Your database'
#      # So you don't have to use root, but you can if you like
#      MYSQL_USER: 'username'
#      # You can use whatever password you like
#      MYSQL_PASSWORD: 'password'
#      # Password for root access
#      MYSQL_ROOT_PASSWORD: 'root password'
#    ports:
#      # <Port exposed> : < MySQL Port running inside container>
#      - '3306:3306'
#    expose:
#      # Opens port 3306 on the container
#      - '3306'
#      # Where our data will be persisted
#    volumes:
#      - ./db_data:/var/lib/mysql




