install.packages("sf", lib="/usr/local/lib/R/site-library")
install.packages("geojsonsf", lib="/usr/local/lib/R/site-library")
install.packages("raster", lib="/usr/local/lib/R/site-library")
install.packages("rgdal", lib="/usr/local/lib/R/site-library")
install.packages("tidyverse", lib="/usr/local/lib/R/site-library")
install.packages("lubridate", lib="/usr/local/lib/R/site-library")
install.packages("lwgeom", lib="/usr/local/lib/R/site-library")
install.packages("here", lib="/usr/local/lib/R/site-library")