version: 1
formatters:
  withtime:
    format: '%(asctime)s %(name)-25s %(levelname)-8s %(message)s'
    datefmt: '%m/%d/%Y %I:%M:%S %p'
  withouttime:
    format: '%(name)-25s %(levelname)-8s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: withouttime
    stream: ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    level: ERROR
    formatter: withtime
    filename: 'logs/shellcast.log'

root:
  level: DEBUG
  handlers: [console, file_handler]